### ISSUE TITLE
Bus Stopping or trying to delete route causing indexoutofrange error

### ISSUE THREAD

**Issue by pionsix** [pcfantasy/TransportVehicleReturnPatch#1]
Although I'm not sure what I did to cause it, I believe I've found a bug with this mod.
I was using it for a few hours without issues until a new route I created caused the game to throw an indexoutofrange error with no details every time a bus reached a stop on this particular route. All buses on this route were empty despite hundreds waiting at the stops. I received the same error if I tried to delete the route or remove the 2nd last bus stop trying to delete the line (No issues deleting stops until only 2 are left). In the end I unsubscribed from this mod which allowed me to delete the route and I have now reinstalled the mod. I'll post here if it occurs again.

In response to the steam comments I've turned on debugging and loaded up an autosave. In the autosave the route was set with 0 frequency through TLM. I initially tried to delete the route by removing stops (which caused the error) then added vehicles back which caused the error when stopping.
[output_log.txt](https://github.com/pcfantasy/TransportVehicleReturnPatch/files/4705689/output_log.txt)
[TransportVehicleReturnPatch.txt](https://github.com/pcfantasy/TransportVehicleReturnPatch/files/4705691/TransportVehicleReturnPatch.txt)

**Comment by pcfantasy** [comment]
Thanks, fixed

https://github.com/pcfantasy/TransportVehicleReturnPatch/commit/8b532d443ecd23df0056b8d8531dbccb0884291f
